<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.manorrock.sphynx</groupId>
        <artifactId>project</artifactId>
        <version>24.11.0</version>
    </parent>
    <artifactId>sphynx-cli-windows-amd64</artifactId>
    <packaging>jar</packaging>
    <name>Manorrock Sphynx - CLI - Windows amd64</name>
    <dependencies>
        <dependency>
            <groupId>com.manorrock.sphynx</groupId>
            <artifactId>sphynx-cli</artifactId>
            <version>${project.version}</version>
            <classifier>all</classifier>
            <scope>compile</scope>
        </dependency>
    </dependencies>    
    <profiles>
        <profile>
            <id>native</id>
            <activation>
                <property>
                    <name>os_and_arch</name>
                    <value>windows-amd64</value>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <version>${native-image-maven-plugin.version}</version>
                        <extensions>true</extensions>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>compile-no-fork</goal>
                                </goals>
                                <phase>package</phase>
                            </execution>
                        </executions>
                        <configuration>
                            <imageName>si</imageName>
                            <buildArgs>-H:+ReportExceptionStackTraces --no-fallback</buildArgs>
                            <mainClass>com.manorrock.sphynx.cli.Cli</mainClass>
                            <skip>false</skip>
                            <verbose>true</verbose>
                        </configuration>
                    </plugin>                    
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
