name: build
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'release-*'
      - 'v*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Build with Maven
      run: mvn -B --ntp package
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Build with Maven
      run: mvn -B -DskipTests=true --ntp install
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to GHCR
      run: |
        cd rest
        mvn -B -DskipTests=true --ntp -P docker install docker:build docker:push
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.6
    - name: Build with Maven
      run:  mvn -B -DskipTests -DskipITs --ntp -P macos package
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Build with Maven
      run: mvn -B -DskipTests -DskipITs --ntp -P windows package
      