name: build
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'release-*'
      - 'v*'
  schedule:
  - cron: "0 0 13 * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Maven
      run: mvn -B package
    - name: Login to Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Philips Hue Bridge container
      run: |
        docker build -f hue/bridge/Dockerfile -t manorrock/sphynx-hue-bridge:latest .
        docker push manorrock/sphynx-hue-bridge:latest
    - name: Build and push Philips Hue A19 White container
      run: |
        docker build -f hue/a19-white/Dockerfile -t manorrock/sphynx-hue-a19-white:latest .
        docker push manorrock/sphynx-hue-a19-white:latest
